### ISSUE TITLE
Class 'InstantArticle' not found

### ISSUE THREAD

**Issue by jshamley** [facebook/facebook-instant-articles-sdk-php#11]
I've followed the installation directions but am running into issues. 

When I run `composer install` I get the following output:
```Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files```

Then after requiring the `vendor/autoload.php` file the `InstantArticle` class is not found.

**Comment by simonengelhardt** [comment]
Thanks for checking out the SDK :+1: 

Have you tried using the full namespace `Facebook\InstantArticles\Elements\InstantArticle`? You can do this in-line or by including with the `use` operator.

**Comment by jshamley** [comment]
Thanks so much for the quick response, I knew it had to be something simple! :)
