### ISSUE TITLE
Interactive element doesn't support iframe width

### ISSUE THREAD

**Issue by jpayette** [facebook/facebook-instant-articles-sdk-php#115]
The documentation for the Interactive element shows many examples of specifying a width for the iframe, and recommends that you do so: https://developers.facebook.com/docs/instant-articles/reference/interactive

When you save an Instant Article that contains an interactive element with no width, you receive the following warning: "HTML Embeds Require Valid Width: HTML Embeds require a valid integer width in order to be displayed properly."

However, the Interactive element in the SDK (https://github.com/facebook/facebook-instant-articles-sdk-php/blob/master/src/Facebook/InstantArticles/Elements/Interactive.php) does not support the width attribute for the iframe. While the class itself does contain a "width" variable, it is used to set the "no-margin" and "column-width" classes, not the integer width of the iframe.

**Comment by everton-rosario** [comment]
Fixed on master.
