### ISSUE TITLE
Vertical alignment on cite and caption

### ISSUE THREAD

**Issue by dodozhang21** [facebook/facebook-instant-articles-sdk-php#116]
I do not see support for classes for vertical alignments `op-vertical-bottom` `op-vertical-center` `op-vertical-top` such as per https://developers.facebook.com/docs/instant-articles/reference/caption

Am I missing something?

**Comment by dodozhang21** [comment]
I created a pr for this https://github.com/facebook/facebook-instant-articles-sdk-php/pull/117

**Comment by everton-rosario** [comment]
This was awesome @dodozhang21 
Just double check the PHPCBF warnings.

You can have it fixed automatically on your PR #117

**Comment by dodozhang21** [comment]
@everton-rosario How do I make it automatically fix it? I fixed them manually.
