### ISSUE TITLE
Google Analytics: Specification mandate value for attribute async

### ISSUE THREAD

**Issue by dragu** [facebook/facebook-instant-articles-sdk-php#129]
Hi,

How do I use Google Analytics with your SDK?

Example from [here](https://developers.facebook.com/docs/instant-articles/sdk/elements) is not working.

My code is

```
		$document = new DOMDocument();
		$analyticsNode = $document->createDocumentFragment();

		$analyticsNode->appendXML($this->analyticsHtmlCode);

		return Analytics::create()->withHTML($analyticsNode);
```

`$this->analyticsHtmlCode` =

```
<script>
window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)};ga.l=+new Date;
//id etc
</script>
<script async src='//www.google-analytics.com/analytics.js'></script>

```

and the error is

`DOMDocumentFragment::appendXML(): Entity: line 6: parser error : Specification mandate value for attribute async`

**Comment by memarv** [comment]
Try async="async"

**Comment by dragu** [comment]
thanks!
