### ISSUE TITLE
Nested div is discarded from transformer.

### ISSUE THREAD

**Issue by esolitos** [facebook/facebook-instant-articles-sdk-php#131]
# Steps required to reproduce the problem

1. Simply use this html snippet with the transformer
```
<div>First div text</div>
<p>First paragraph text</p>
<div>
  <div>A nested div</div>
  <p>Plus a nested paragraph</p>
</div>
```

# Expected Result

* Same html as input

# Actual Result

* ```<p>First div text</p><p>First paragraph text</p>```

# Notes

I am using facebook-instant-articles-sdk-php within a Drupal 7 website via the [fb_instant_articles module](https://www.drupal.org/project/fb_instant_articles), however from what I was able to observe the issue relies in the Transformer class.

**Comment by everton-rosario** [comment]
Instant Article markup doesn't apply any rendering to <div> tags. 
Any text should be within the allowed tags that can be checked here: https://developers.facebook.com/docs/instant-articles/reference

The expected result on your case would be:
<p>First div text</p>
<p>First paragraph text</p>
<p>A nested div</p>
<p>Plus a nested paragraph</p>

To transform your <div> tags into paragraph, you will need to add a transformation rule into your rules.json.

The rule will be something like:

  ```
    {
        "class": "ParagraphRule",
        "selector": "div"
    }
```

**Comment by esolitos** [comment]
The rule you have suggested is actually defined, however the nested content is just dropped, isn't this wrong?

At the moment the only way i was able to make it work is to add a passthrough rule to anything below a div, however i'm not sure it's the right approach: 
```
{
    'class': 'PassThroughRule',
    'selector': "//div[*]"
}
```
