### ISSUE TITLE
Getting "DEBUG =======." when using Transform

### ISSUE THREAD

**Issue by fatonsopa** [facebook/facebook-instant-articles-sdk-php#135]
I have implemented Instant Article's API and I'm getting a DEBUG text when transforming the article.

# Steps required to reproduce the problem

1. Create a Instant Article Instance
2. Append Header Data
3. Transform a normal html (article content) via Transformer object
4. Connect to Client
5. Render Instant Article
6. Import Article

You can find the code here:
http://paste.ofcode.org/36RBimG7nmeuiXCTCHGaQiC

# Expected Result
(boolean)
* 

# Actual Result

I'm getting a "DEBUG =======.." row for each of DOM Elements in the article's content!

This is happening right after the following row:
$transformer->transform($instant_article, $document);

Bug was also reported in Facebook:
https://developers.facebook.com/bugs/1756986321207897/

**Comment by everton-rosario** [comment]
@fatonsopa Have you turned off the debugger?

There is the log4php that outputs few instruction lines on the standard output if no logger appender is defined.

Try to set this on your project:

`
     \Logger::configure(
            [
                'rootLogger' => [
                    'appenders' => ['facebook-instantarticles-transformer']
                ],
                'appenders' => [
                    'facebook-instantarticles-transformer' => [
                        'class' => 'LoggerAppenderConsole',
                        'threshold' => 'INFO',
                        'layout' => [
                            'class' => 'LoggerLayoutSimple'
                        ]
                    ]
                ]
            ]
        );
`


Feel free to reopen if this doesn't fit well.

**Comment by fatonsopa** [comment]
Hey @everton-rosario, 

Thanks, that's solved the issue :)

Regards,
