### ISSUE TITLE
Interactive inside paragraph

### ISSUE THREAD

**Issue by basarkar** [facebook/facebook-instant-articles-sdk-php#139]
This is not an issue rather a feature request.

**Comment by everton-rosario** [comment]
@basarkar Thanks for contributing.

Can you provide more details about this?
Try to provide who your html markup is, and then we can check how we can implement this.
Please reopen when getting it more detailed, please.

**Comment by basarkar** [comment]
From:
<p>lorem ipsum<iframe src="http://www.google.com"></frame>Hello world</p>
To:
<p>lorem ipsum</p>
<figure class="op-interactive">
        <iframe src="http://www.google.com" class="no-margin"></iframe>
 </figure>
<p>Hello world</p>

**Comment by everton-rosario** [comment]
@basarkar Is it possible for you to have it in separated paragraphs before sending to Transformer?

something like:
```html
<p>lorem ipsum</p>
<iframe src="http://www.google.com">
<p>Hello world</p>
```

**Comment by basarkar** [comment]
I guess I have to do dom manipulation before sending it to the transformer. If you want then I can try to create a rule class like InteractiveInsideParagraphRule.php same as like ImageInsideParagraphRule.php

**Comment by basarkar** [comment]
Thanks @everton-rosario
