### ISSUE TITLE
Move hard-coded \Logger calls to new SDK Logger interface

### ISSUE THREAD

**Issue by scottrigby** [facebook/facebook-instant-articles-sdk-php#14]
This issue is just a place to get the discussion started. I've already pinged @simonengelhardt about it and sounds like this was a quick way to get going but the intent was to refine this at some point anyway. We can really use it for https://github.com/BurdaMagazinOrg/module-fb_instant_articles. If we agree on a direction, I can help with a PR.

**Comment by scottrigby** [comment]
Would you guys be willing to have the SDK depend on [Psr\Log](https://packagist.org/packages/psr/log)?

**Comment by everton-rosario** [comment]
Im not sure if we want to add more dependencies to this SDK.
Do you @scottrigby wants to work on this: #21 ?

The #14 and #21 are related and we could work on this as a new feature, adding a Logger abstraction layer and updating Transformer to log events in a separated buffer.

**Comment by chekalskiy** [comment]
There are several issues with \Logger:
- sometimes our deploy fails because of inavailability of `https://packagist.org/packages/apache/log4php`
- \Logger echoes Debug info by default

Could you please replace it with Psr\Log?

**Comment by everton-rosario** [comment]
PR #304 for this.
