### ISSUE TITLE
Transformer Error

### ISSUE THREAD

**Issue by codeman2872** [facebook/facebook-instant-articles-sdk-php#142]
I just updated my SDK and my transformer-rules.json file is apparently gone. Is there an updated version?

**Comment by everton-rosario** [comment]
@codeman2872 Your transformer-rules.json should be like this one:
https://raw.githubusercontent.com/facebook/facebook-instant-articles-sdk-php/master/tests/Facebook/InstantArticles/Transformer/CMS/wp-rules.json

You can copy/paste over your transformation-rules.json file.

Feel free to reopen if the issue still happens to you.
