### ISSUE TITLE
Submission Issue

### ISSUE THREAD

**Issue by codeman2872** [facebook/facebook-instant-articles-sdk-php#144]
I am having a recurring issue where an attempt to submit a new article results in the following error:

# Steps required to reproduce the problem

1. Create formatted HTML
2. Run through transformer
3. Submit to API

# Expected Result

* Accepted new article

# Actual Result

* Error code as show below

```
DEBUG - ===========================
DEBUG - 
DEBUG - ===========================
DEBUG - <html lang="en" prefix="op: http://media.facebook.com/op#">

```

**Comment by everton-rosario** [comment]
@codeman2872 
Please, can you share here more info about your transformation problem?

We need you to click in the link "**[Toggle debug information]**" in the "Instant Articles" meta-box and then copy and past the both editor's text: "**Source Markup**" and "**Transformed Markup**"

Also, if you can, provide the custom rules you've configured for your makrup.

I'll reopen this issue, with more info you'll provide.
