### ISSUE TITLE
composer.json needs update

### ISSUE THREAD

**Issue by boredom2** [facebook/facebook-instant-articles-sdk-php#164]
The composer.json still links to facebook-php-sdk, which has been renamed/moved to facebook/graph-sdk. Please change the Requirement, so that only facebook/graph-sdk is included in external projects (otherwise, there are two Facebook SDKs installed).

**Comment by anibalsanchez** [comment]
I agree. This repo must be updated to have a consistent configuration.

**Comment by everton-rosario** [comment]
@boredom2 @anibalsanchez Thanks for bringing that up.
We have this addressed and will be included on the next release.

I'll close, since this is covered in another (internal - sorry but can't link it here) task.

**Comment by anibalsanchez** [comment]
Great!

**Comment by dragu** [comment]
Thanks
