### ISSUE TITLE
No any div class for "recipe plugin"

### ISSUE THREAD

**Issue by marciatack** [facebook/facebook-instant-articles-sdk-php#173]
# Steps required to reproduce the problem

I have one recipe site and my recipe content not showing in facebook instant article post .
Showing this error : 
No rules defined for div class="mpprecipe-container-border" in the context of InstantArticle

Please let me know how to create rule for this ?

**Comment by thomaswn** [comment]
This should generally do it
{
    "rules":
    [{
        "class": "PassThroughRule",
        "selector": "div.mpprecipe-container-border"
    }
}
However I've noticed that some elements that are not contained within a paragraph element can fail, so wrapping it within a <p> tag could solve the issue as well.

**Comment by everton-rosario** [comment]
@marciatack 
Please, can you share here more info about your transformation problem?

I need the source markup example (regular HTML file you are trying to transform).

Im closing this for now, until you provide more info.
