### ISSUE TITLE
Error in Login with FAcebook

### ISSUE THREAD

**Issue by ettoregabrielli** [facebook/facebook-instant-articles-sdk-php#174]
When connecting to Facebook, after set ID and Code of the APP

Cannot load URL: domain of this url is not incluent in app domains.

(this is my translation of italian:
"Impossibile caricare l'URL: Il dominio di questo URL non è incluso nei domini dell'applicazione. Per essere in grado di caricare questo indirizzo, aggiungi tutti i domini e sottodomini della tua applicazione nel campo "Domini applicazione" nelle impostazioni della tua applicazione.")

# Steps required to reproduce the problem

1. Set up plugin.
2. Disable plugin
3. Re-enable plugin
4. Go to setting, set App ID and secret code
5. Try to Login with Facebook

# Expected Result

Login with facebook 

# Actual Result

Error as wrote up.

**Comment by everton-rosario** [comment]
@ettoregabrielli Sorry for the late response.

Your case, actually doesn't seem to be related to an issue on the SDK, but to the configurations between your page and your APP setup, as I've already noticed on a few partners configuring the login flow.

If you feel it is harder to do all the flow, you can: 
Do it manually on your Facebook: 
1. Select your page on top right arrow down
2. Go to publishing tools
3. Select Instant Articles > Configuration

or 

You can check how we've implemented this login flow on our official plugin: github.com/Automattic/facebook-instant-articles-wp


I hope this fits your case.
Feel free to reopen this.
