### ISSUE TITLE
Support for RTL

### ISSUE THREAD

**Issue by Vinlock** [facebook/facebook-instant-articles-sdk-php#175]
# Steps required to reproduce the problem

There does not seem to be a way to activate RTL in the HTML tag.

# Expected Result

* `<html dir="rtl">`

# Actual Result

* `<html>`

**Comment by everton-rosario** [comment]
@Vinlock thanks for flagging this.

We prioritized this and now have it ready on master. This will be released on the next version of the plugin, but hopefully you can upgrade your version with the master version.

**Comment by Vinlock** [comment]
@everton-rosario No problem. Thank you! I will upgrade to master.
