### ISSUE TITLE
Force OG Re-scrape on post update

### ISSUE THREAD

**Issue by demoive** [facebook/facebook-instant-articles-sdk-php#182]
Follow best practice and force a re-scrape of the OG tags whenever a post is updated.

https://developers.facebook.com/docs/sharing/opengraph/using-objects#update

**Comment by jppgks** [comment]
@demoive Looking into this issue, I tried calling the API endpoint you mentioned for updating an object and re-scraping it. However, I got the following error. Did I use the wrong access token?

```json
{
  "error": {
    "message": "Unsupported post request. Object with ID '383554125332198' does not exist, cannot be loaded due to missing permissions, or does not support this operation. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api",
    "type": "GraphMethodException",
    "code": 100,
    "fbtrace_id": "CyP7benqDVg"
  }
}
```

**Comment by jppgks** [comment]
@demoive Is the documentation for that API endpoint still correct? When calling the endpoint using the [Graph API Explorer](https://developers.facebook.com/tools/explorer/), the data isn't updated.
