### ISSUE TITLE
Documentation Issue

### ISSUE THREAD

**Issue by ronaldgj** [facebook/facebook-instant-articles-sdk-php#183]
Hi Guys!

I found an issue in the Documentation of the Transformer Rules. For the 'Caption' you can give a property of the 'size'. The documentation shows me:

```
type = "exists" for one of either size options:
op-size-medium
op-size-large
op-size-extra-large
```

But when I look in the source code of the 'Caption Element' the word 'size' is missing, so it won't work!

```
// Font size
    const SIZE_MEDIUM = 'op-medium';
    const SIZE_LARGE = 'op-large';
    const SIZE_XLARGE = 'op-extra-large';
```

Hope it will help you all.

**Comment by everton-rosario** [comment]
@ronaldgj Thanks for flagging.

The size you are looking for is the $font_size.
So you can use the Caption::withFontsize() method to set your caption size.
This is also covered on CaptionRule class, which transforms Caption based on the configuration Rules.

Is this the thing you were looking for?

Sorry for the long wait on this.


Let me know if you have any more issues on this.
