### ISSUE TITLE
Facebook\Exceptions\FacebookServerException - POST - An unknown error has occurred.

### ISSUE THREAD

**Issue by Vinlock** [facebook/facebook-instant-articles-sdk-php#188]
This error is very vague and I cannot find any docs on what this could me for me to investigate it properly. Can anyone give me an idea?

Thanks!

**Comment by simonengelhardt** [comment]
Hi @Vinlock,

Could you provide a little more context on when you are getting this error? If you could fill out the issue template, that would be great. Thanks.

```
# Steps required to reproduce the problem

1. 
2. 
3. 

# Expected Result

* 

# Actual Result

* 
```

**Comment by Vinlock** [comment]
# Steps required to reproduce the problem

1. Install Facebook Instant Articles via composer
2. Apply the APP ID, APP SECRET, and Never expiring ACCESS TOKEN
3. Attempt to post an instant article

# Expected Result

* Instant article is posted.

# Actual Result

* Facebook\Exceptions\FacebookServerException - POST - An unknown error has occurred.

**Comment by Vinlock** [comment]
`object(Requests_Response)[68]
  public 'body' => string '{"error":{"message":"An unknown error has occurred.","type":"OAuthException","code":1,"fbtrace_id":"AMQDUrqJY8C"}}' (length=114)
  public 'raw' => string 'HTTP/1.1 500 Internal Server Error
WWW-Authenticate: OAuth "Facebook Platform" "unknown_error" "An unknown error has occurred."
Access-Control-Allow-Origin: *
Pragma: no-cache
Cache-Control: no-store
facebook-api-version: v2.8
Expires: Sat, 01 Jan 2000 00:00:00 GMT
Content-Type: application/json; charset=UTF-8
x-fb-trace-id: AMQDUrqJY8C
x-fb-rev: 2746767
X-FB-Debug: aXV6I+kvD6p6EEHhURFbVRLwkbdEP6IXJeHbAtiYiDsOpcie1j7es7e+/jE68dZV90JdWea2EVDoV+EjQYnGXA==
Date: Sun, 18 Dec 2016 05:24:06 GMT
Connec'... (length=662)
  public 'headers' => 
    object(Requests_Response_Headers)[70]
      protected 'data' => 
        array (size=12)
          'www-authenticate' => 
            array (size=1)
              ...
          'access-control-allow-origin' => 
            array (size=1)
              ...
          'pragma' => 
            array (size=1)
              ...
          'cache-control' => 
            array (size=1)
              ...
          'facebook-api-version' => 
            array (size=1)
              ...
          'expires' => 
            array (size=1)
              ...
          'content-type' => 
            array (size=1)
              ...
          'x-fb-trace-id' => 
            array (size=1)
              ...
          'x-fb-rev' => 
            array (size=1)
              ...
          'x-fb-debug' => 
            array (size=1)
              ...
          'date' => 
            array (size=1)
              ...
          'content-length' => 
            array (size=1)
              ...
  public 'status_code' => int 500
  public 'protocol_version' => float 1.1
  public 'success' => boolean false
  public 'redirects' => int 0
  public 'url' => string 'https://graph.facebook.com/v2.8/1689605241284159/instant_articles' (length=65)
  public 'history' => 
    array (size=0)
      empty
  public 'cookies' => 
    object(Requests_Cookie_Jar)[53]
      protected 'cookies' => 
        array (size=0)
          empty`

**Comment by simonengelhardt** [comment]
Thanks for the info @Vinlock. That output from the POST is especially useful. We'll take a look.

**Comment by everton-rosario** [comment]
Error was released and solved by reactivating the internal publishing account.
It was disabled because of a policy infringement that was resolved and now the account is able to publish again.
