### ISSUE TITLE
Can we have the ability to remove a child from an InstantArticle class object?

### ISSUE THREAD

**Issue by despinoUY** [facebook/facebook-instant-articles-sdk-php#191]
As @dashaluna asked in other Facebook project (https://github.com/Automattic/facebook-instant-articles-wp/issues/529), is there any chance to have a function to remove a child from an InstantArticle object? If it's not, a function to load a completely different array of Element objects as Children would be great!

Greets!

**Comment by everton-rosario** [comment]
This is fixed and will be on release v1.5.5
