### ISSUE TITLE
HTML tags as &lt;tag&gt; when importArticle()

### ISSUE THREAD

**Issue by acampitos** [facebook/facebook-instant-articles-sdk-php#194]
# Steps required to reproduce the problem

1. Create an instant article with PHP
```
$article = InstantArticle::create();
....
```
Create all necesary fields for the instant article
2. When creating paragraphs, hardcode a text with html tags inside: for example:
```
$article->addChild(
	Paragraph::create()
	->appendText("<strong>This is a test</strong>")
);
```
3. call `$client->importArticle($article);` to import the article to Facebook page

# Expected Result

* The expected result is an instant article in Facebook page with `<strong>This is a test</strong>` inside a paragraph

# Actual Result

* `<p>&#13;&lt;strong&gt;</p>` in the article. Visible code in the article so the article will never pass revision

It happens with every html tag

![seleccion_256](https://cloud.githubusercontent.com/assets/11631262/22141614/21cdeaa2-def3-11e6-8e28-f9d738d814bd.png)

# More info about debugging

If I debug the article inside the importArticle function (before calling `$article->render()` ) has well formed tags but when calling to `$article->render()` in
          ` 'html_source' => $article->render(),` (LINE 101 - Client.php) 
this content is changed from `<strong>` to `&lt;strong&gt;` for example.

So the replacement is done inside render() function in Element.php:
           `public function render($doctype = '', $formatted = false)`

**Comment by diegoquinteiro** [comment]
Hi @acampitos,

The `appendText()` method is not intended to understand tags. This is the expected behavior.

The right way would be:

```php
$article->addChild(
	Paragraph::create()
	    ->appendText(
                    Bold::create()
                        ->appendText("This is a test")
                )
);
```

If you want to convert HTML into Element objects automatically, please use the Transformer component instead.
