### ISSUE TITLE
"op-ad-default" is stripped by the Transformer?

### ISSUE THREAD

**Issue by mrgray** [facebook/facebook-instant-articles-sdk-php#197]
# Steps required to reproduce the problem

This is the input,
```
<header>
  ...
  <figure class="op-ad">
    <iframe width="300" height="250" style="border:0; margin:0;" src="https://www.facebook.com/adnw_request?placement=xxx&adtype=banner300x250"></iframe>
  </figure>

  <figure class="op-ad">
    <iframe width="300" height="250" style="border:0; margin:0;" src="https://www.facebook.com/adnw_request?placement=xxx&adtype=banner300x250"></iframe>
  </figure>

  <figure class="op-ad op-ad-default">
    <iframe width="300" height="250" style="border:0; margin:0;" src="https://www.facebook.com/adnw_request?placement=xxx&adtype=banner300x250"></iframe>
  </figure>

  <figure class="op-ad">
    <iframe width="300" height="250" style="border:0; margin:0;" src="https://www.facebook.com/adnw_request?placement=xxx&adtype=banner300x250"></iframe>
  </figure>
  ...
</header>
```

# Expected Result
```
<header>
  ...
  <section class="op-ad-template">
    <figure class="op-ad">
      <iframe width="300" height="250" style="border:0; margin:0;" src="https://www.facebook.com/adnw_request?placement=xxx&adtype=banner300x250"></iframe>
    </figure>
    <figure class="op-ad">
      <iframe width="300" height="250" style="border:0; margin:0;" src="https://www.facebook.com/adnw_request?placement=xxx&adtype=banner300x250"></iframe>
    </figure>
    <figure class="op-ad op-ad-default">
      <iframe width="300" height="250" style="border:0; margin:0;" src="https://www.facebook.com/adnw_request?placement=xxx&adtype=banner300x250"></iframe>
    </figure>
    <figure class="op-ad">
      <iframe width="300" height="250" style="border:0; margin:0;" src="https://www.facebook.com/adnw_request?placement=xxx&adtype=banner300x250"></iframe>
    </figure>
  </section>
  ...
</header>
```

# Actual Result
```
<header>
  ...
  <section class="op-ad-template">
    <figure class="op-ad">
      <iframe width="300" height="250" style="border:0; margin:0;" src="https://www.facebook.com/adnw_request?placement=xxx&adtype=banner300x250"></iframe>
    </figure>
    <figure class="op-ad">
      <iframe width="300" height="250" style="border:0; margin:0;" src="https://www.facebook.com/adnw_request?placement=xxx&adtype=banner300x250"></iframe>
    </figure>
    <figure class="op-ad">
      <iframe width="300" height="250" style="border:0; margin:0;" src="https://www.facebook.com/adnw_request?placement=xxx&adtype=banner300x250"></iframe>
    </figure>
    <figure class="op-ad">
      <iframe width="300" height="250" style="border:0; margin:0;" src="https://www.facebook.com/adnw_request?placement=xxx&adtype=banner300x250"></iframe>
    </figure>
  </section>
  ...
</header>
```

This leads to "_General Warnings: Ad default template is not specified: Ad default template is not specified, use the last last one in ad section block instead_".

Am I missing something?

**Comment by everton-rosario** [comment]
Hello @mrgray! I guess you missed a few things about the ad placement.

You gotta check this documentation about [ad placement](https://developers.facebook.com/docs/instant-articles/monetization/ad-placement)

As you can see, you gotta set if you will have the auto placement (as I see you are looking for it).
```
<head>
  <meta property="fb:use_automatic_ad_placement" content="true">
</head>
```

Also, the warning message you are receiving is about the missing property flagging the default ad, for the auto placement.
You can see the full doc on the link or this snippet of code:
```
<section class="op-ad-template">
        <!-- Ads to be automatically placed throughout the article -->
        <figure class="op-ad">
          <iframe src="https://www.adserver.com/ss;adtype=banner300x250&adslot=1" height="300" width="250"></iframe>
        </figure>
        <figure class="op-ad op-ad-default"> <!-- THIS IS THE OP AD DEFAULT the warning message is missing -->
          <iframe src="https://www.adserver.com/ss;adtype=banner300x250&adslot=2" height="300" width="250"></iframe>
        </figure>
        <figure class="op-ad">
           <iframe src="https://www.adserver.com/ss;adtype=banner300x250&adslot=3" height="300" width="250"></iframe>
        </figure>
      </section>
```

I'll close this issue, since this answer might answer your questioning. Let me know/reopen if this isn't enough.

Thanks!

**Comment by mrgray** [comment]
Hey @everton-rosario!

I actually do have **fb:use_automatic_ad_placement** defined with **op-ad-default**. The **op-ad-default** is stripped when it goes through the Transformer.

**Comment by everton-rosario** [comment]
Can't you add the ADs after the transformation?
Are you using this in any CMS (like Wordpress? Drupal?)
Can you give little more details on the environment you have set?

**Comment by mrgray** [comment]
- When you say add the ads later, do you mean modify the InstantArticle returned by Transformer's transform method? Me likey - I'll give this a shot. Still odd that the Transformer drops that default ad tag.

- We're using a highly modified version of the http://silverstripe.org/ CMS.

- I'll be happy to help. Could you tell me specifically what environment details would help? Adding the ones that I think might help,

PHP Version 5.6.15
libxml Version 2.9.2
cURL support enabled
cURL Information 7.38.0

**Comment by everton-rosario** [comment]
Yes, it is perfectly doable to change it later (After transformation occurs).
Now that you've mentioned how the process is happening, we didn't built the rules for interpreting the ads before transformation. On WordPress plugin for example, we add it after transformation occurs. 

So I'd go with that solution. (we now have few add/remove methods to the [InstantArticle](https://github.com/facebook/facebook-instant-articles-sdk-php/blob/master/src/Facebook/InstantArticles/Elements/InstantArticle.php) Element and [Header](https://github.com/facebook/facebook-instant-articles-sdk-php/blob/master/src/Facebook/InstantArticles/Elements/Header.php).

Those are the ones you might be looking for on building and setting up your Ads.
