### ISSUE TITLE
How to translate Instant Article and how to enable 'Swipe for more' function?

### ISSUE THREAD

**Issue by Kelly27** [facebook/facebook-instant-articles-sdk-php#202]
I need my Instant Article to multilingual so how to make Instant Article multilingual?
By the way, how to enable the 'swipe for more' function?

**Comment by everton-rosario** [comment]
@Kelly27 Sorry, but still we don't support multi lingual posts nor Instant Articles.
The best way to support this is to have different pages for different crowds. This way you can keep the Language A speakers into page A and Language B speakers into page B. Then it will be just a matter of posting to those people separately.
