### ISSUE TITLE
Support: Transformer rules definition for PullquoteRule (w/ Cite)

### ISSUE THREAD

**Issue by kolibrid** [facebook/facebook-instant-articles-sdk-php#206]
Hello, we have been trying to transform the following code to a PullQuote using the transformer, however it seems to be a but unintuitive how the rules are working.
As soon as the html structure is not simple it seems there are may and many rules to be added to get the content into the FB Instant Article.

This is our initial html structure:

```
<div class="ckeditor-widgets-quotebox align-center">
    <div class="quotebox-inner">
        <div class="quotebox-content">
            <div class="quotebox-content-inner">Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore.</div>
        </div>
        <div class="quotebox-author">
            <div class="quotebox-author-inner">
                <p>Author Name</p>
            </div>
        </div>
    </div>
</div>
```

# Expected Result
```
<aside>
  Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore.
  <cite>Author Name</cite>
</aside>
```

# Actual Result
* Nothing shows up in the transformed article.

We have tested with several rules, we're using the [drupal module](https://www.drupal.org/project/fb_instant_articles) as base, however this shouldn't matter since it simply uses this sdk behind the scenes.
We made many attempts but nothing seems to be working, before we implement a custom rule class I wanted to ask here. This is one of the _several_ attempts we have tried:

```
  ...
  {
    'class' => 'PassThroughRule',
    'selector' => 'div.quotebox-inner > div.quotebox-content > div.quotebox-content-inner'
  },
  {
    'class' => 'PullquoteRule',
    'selector' => 'div.ckeditor-widgets-quotebox'
  },
  {
    'class' => 'PullquoteCiteRule',
    'selector' => "div.quotebox-inner > div.quotebox-author > div.quotebox-author-inner > p"
  }
  ...
```

**Comment by pestevez** [comment]
You could try with something like:

```javascript
{
  "rules":[
    {
      "class":"PassThroughRule",
      "selector":"div.ckeditor-widgets-quotebox, div.quotebox-content, div.quotebox-author, div.quotebox-content-inner"
    },
    {
      "class":"PullquoteRule",
      "selector":"div.quotebox-inner"
    },
    {
      "class":"PullquoteCiteRule",
      "selector":"div.quotebox-author-inner"
    }
  ]
}
```

I kept the selectors simple, but you can also use stricter selectors like `div.ckeditor-widgets-quotebox > div.quotebox-inner` for the PullquoteRule.

**Comment by pestevez** [comment]
@kolibrid - I am closing this issue now, but feel free to reopen if you need more information. Thanks

**Comment by kolibrid** [comment]
Thanks @pestevez !

Your code helped me understand how to use the transformer rules. The solution for my problem is actually the following (almost what you suggested):

```
{
  "rules":[
    {
      "class":"PassThroughRule",
      "selector":"div.ckeditor-widgets-quotebox, div.quotebox-content, div.quotebox-author, div.quotebox-content-inner, div.quotebox-author-inner p"
    },
    {
      "class":"PullquoteRule",
      "selector":"div.quotebox-inner"
    },
    {
      "class":"PullquoteCiteRule",
      "selector":"div.quotebox-author-inner"
    }
  ]
}
```
