### ISSUE TITLE
Authentication Required during composer install

### ISSUE THREAD

**Issue by martwana** [facebook/facebook-instant-articles-sdk-php#211]
# Steps required to reproduce the problem

1. Add facebook/facebook-instant-articles-sdk-php to composer.json
2. Run composer install

# Expected Result

* It is expected that composer will install the package.

# Actual Result

* Composer stops, and prompts for authentication for the apache/log4php dependency. 

```
Loading composer repositories with package information
Installing dependencies from lock file
Package operations: 44 installs, 0 updates, 0 removals
  - Installing apache/log4php (2.3.0): Cloning 8c6df2481c
    Authentication required (git-wip-us.apache.org):
      Username:

```

This seems to be due to https:// connections being for "Committers" only. This can be seen on the website for the repo.

> https://git-wip-us.apache.org/

**Comment by everton-rosario** [comment]
Hey, thanks for reporting this.
This is an old dependency unchanged.
This is hosted in packagist: https://packagist.org/packages/apache/log4php

I couldn't reproduce this issue. Can you provide a little more info about this permission denied issue?
Looks like it is trying to clone repository then building the package. This might be something related with your environment. 

Can you double check if the points I've raised makes sense?

**Comment by everton-rosario** [comment]
@martwana Check this out: https://github.com/composer/composer/issues/3908

This is not related to our repo, itself.
