### ISSUE TITLE
Instant article doesn't show in facebook page.

### ISSUE THREAD

**Issue by webcrazy** [facebook/facebook-instant-articles-sdk-php#214]
### Steps required to reproduce the problem

1. Published instant articles. ( with live ) not unpublished.

### Expected Result

* it should show in facebook page 

### Actual Result

* it doesn't show.

**Comment by everton-rosario** [comment]
Publishing to Instant Articles means that the article you've sent will be available as Instant Article for anyone who shares that link.
Lets assume this is your article URL: http://domain.com/my-article

If someones share this link into Facebook news feed or Messenger, it will render as a regular Web link, and when users click on this story, it will open on the browser.

What changes when you submit this as Instant Articles, it will become available as instant article, so anyone will be able to click on the previous shared news feed links and see it as Instant Article.

**Comment by webcrazy** [comment]
Hi @everton-rosario Thanks for your reply.

What I mean is I already implement to import instant articles via facebook instant articles SDK when I create a post on my website.

I already submit 5 articles for review as well and confirmed.

Here's my screenshot for approve.
![live](https://cloud.githubusercontent.com/assets/5352704/25861068/a8567082-3509-11e7-9ee2-2d58f8b6454a.png)

As you can see, it's already live. And I can check from facebook page manager and it looks fine but it doesn't show in my facebook page.
I wonder why.

**Comment by webcrazy** [comment]
Sorry I miss this description from facebook. I gotta share that article to page.

![screen shot 2017-05-27 at 9 14 47 am](https://cloud.githubusercontent.com/assets/5352704/26517711/b9c4fa50-42c4-11e7-9912-c0a339ea7501.png)

https://developers.facebook.com/docs/instant-articles/quickstart#sharing
