### ISSUE TITLE
How to embed custom localized font?

### ISSUE THREAD

**Issue by webcrazy** [facebook/facebook-instant-articles-sdk-php#216]
I'd like to add custom embedded font to facebook-instant-articles because in order to show our language correctly, I need to embed custom font rather than default fonts.

Is that possible? Any help would be every appreciated.

**Comment by KhunHtetzNaing** [comment]
me too
i want to know how to use custom font in facebook instant articles :D

**Comment by webcrazy** [comment]
@KhunHtetzNaing Instant article comes with default font Georgia. It's not compatible with Zawgyi font. not sure about unicode. I haven't tested. But changing styling with 
Helvetica Neue was rendered correctly with Zawgyi for me.

**Comment by KhunHtetzNaing** [comment]
Woow
This way work fine <3
Thank you bro

**Comment by webcrazy** [comment]
You're welcome. bro 👍

**Comment by kolunar** [comment]
@webcrazy @KhunHtetzNaing FYI
![instant-article-configuration-custom-typeface-missing](https://user-images.githubusercontent.com/7478925/28515142-10d5b8de-704c-11e7-8f85-4efcc6aea036.png)

**Comment by phongtattuan** [comment]
hi @kolunar,
how can you display the `Zawgyi-One` and `Manage custom font` on typeface
my page don't have `Manage custom font` option

thank you.

**Comment by koaungduwun** [comment]
@phongtattuan 
Ask a question/requesting for the feature at https://business.facebook.com/direct-support/
![fbia-direct-support](https://user-images.githubusercontent.com/28386342/32434237-dcb84464-c30b-11e7-8c5a-5bc9c6420f60.png)

**Comment by KhunHtetzNaing** [comment]
not have direct support menu :'(
@koaungduwun ![image](https://user-images.githubusercontent.com/12862097/32435443-548ec820-c30f-11e7-9cfb-8ccbf3be950d.png)

**Comment by sbbic** [comment]
We also don't have the "Direct Support" option - any way to get this enabled on our account? The default fonts for the Khmer language look horrible.
