### ISSUE TITLE
Class undefined: Facebook\InstantArticles\Elements\AnimatedGif in Elements/InstantArticle.php on line 196

### ISSUE THREAD

**Issue by fariasf** [facebook/facebook-instant-articles-sdk-php#23]
Hi!

When I try to run the tests I see the following error:

`Fatal error: Class undefined: Facebook\InstantArticles\Elements\AnimatedGif in /var/www/mysite/src/sites/all/modules/contrib/fb_instant_articles/vendor/facebook/facebook-instant-articles-sdk-php/src/Facebook/InstantArticles/Elements/InstantArticle.php on line 196`

I'm not familiar with the code base, but I tried to find that class and only found facebook-instant-articles-sdk-php/src/Facebook/InstantArticles/Elements/AnimatedGIF.php. If I change that line, replacing the class name to `AnimatedGIF` as defined in that file, the issue disappears.

Is this an error or am I doing something wrong?

Thanks!

**Comment by diegoquinteiro** [comment]
Hi @fariasf, thank you so much for your feedback. That was actually a bug on v1.0.0. It should now be fixed on v1.0.1 and on master.

Can you check if that works for you?

**Comment by diegoquinteiro** [comment]
Closing as the same issue was marked resolved on WordPress plugin implementation of the SDK:

https://wordpress.org/support/topic/fatal-error-class-facebookinstantarticleselementsanimatedgif-not-found?replies=4
