### ISSUE TITLE
Transformer rule help needed for tags withing Blockquote

### ISSUE THREAD

**Issue by kevinlisota** [facebook/facebook-instant-articles-sdk-php#232]
Our site uses both blockquotes and pull quotes. Pull quotes are always brief, either 1 or two sentences. Blockquotes often contain multiple paragraphs and sometimes contain ordered or unordered lists.

I can't figure out how to get the transformer rules to work on this. Here is the syntax coming from the WordPress editor

The following mashes into one giant paragraph blockquote.
```
<blockquote>
<p>some text</p>
<p>some text</p>
<p>some text</p>
</blockquote>
```
If you add in a `<ul>` or `<ol>` inside of the blockquote, transformation fails with a "no rules in the context of Blockquote".
```
<blockquote>
<p>some text</p>
<ul>
<li>a list></li>
</ul>
<p>some text</p>
</blockquote>
```
I'm stuck on this one. How do I maintain paragraph and list tags inside of a blockquote to maintain the expected formatting?

**Comment by everton-rosario** [comment]
@kevinlisota we don't support lists inside `<blockquote>`
Can you perform some changes into this structure?

I also guess that these rules should do the trick for you, but be sure it doesn't conflicts with regular lists.

```
{
   "class": "PassThroughRule",
   "selector": "ul"
},
{
   "class":  "ParagraphRule",
   "selector": "li"
}
```

Let me know if this works for you.
Im closing, for now, but you can reopen if it doesn't work for you.
