### ISSUE TITLE
Markup with h3-h6 elements looses all h3-h6 elements when run through the transformer

### ISSUE THREAD

**Issue by m4olivei** [facebook/facebook-instant-articles-sdk-php#234]
# Steps required to reproduce the problem

1. Pass markup with h3-h6 elements through the Transformer.

# Expected Result

* h3-h6 elements should be retained in the output, if indeed the Facebook Instant Articles format allows for h3-h6 in the body. I coudln't find anything definitive one way or the other in the documentation. Please clarify.

# Actual Result

* All h3-h6 elements are lost in the output.

I noticed that there is an [H3 element](https://github.com/facebook/facebook-instant-articles-sdk-php/blob/master/src/Facebook/InstantArticles/Elements/H3.php) in the SDK, however there is not a corresponding H3Rule. There is no H4-H5 element, nor are there corresponding rules. Should there be?

**Comment by m4olivei** [comment]
Even using a custom rule, the `InstantArticle` class doesn't allow an `H3` element: https://github.com/facebook/facebook-instant-articles-sdk-php/blob/master/src/Facebook/InstantArticles/Elements/InstantArticle.php#L307-L328

**Comment by m4olivei** [comment]
Humm now I'm confused. According to the Instant Article editor, h3-h6 are not allowed:

![drupal instant articles development 2017-07-07 13-28-15](https://user-images.githubusercontent.com/191049/27969278-3fde1f68-6318-11e7-9d9c-55fe81263a16.png)

So perhaps this is a non-issue, other that the [H3 element](https://github.com/facebook/facebook-instant-articles-sdk-php/blob/master/src/Facebook/InstantArticles/Elements/H3.php) should be removed?

**Comment by pestevez** [comment]
I believe only h1 and h2 are supported as headings in the article body. In addition to the warnings you show in the markup, the Instant Articles Style Editor only shows the Primary Heading (h1) and the Secondary Heading (h2):

![image](https://user-images.githubusercontent.com/18663703/27974933-28339bac-632e-11e7-8595-bd17809a7a11.png)

**Comment by pestevez** [comment]
The [H3 Element](https://github.com/facebook/facebook-instant-articles-sdk-php/blob/master/src/Facebook/InstantArticles/Elements/H3.php) is still needed because it is used to generate the Header's [Kicker](https://developers.facebook.com/docs/instant-articles/reference/cover).

I am closing this issue now, but please feel free to reopen if you need additional information.

**Comment by m4olivei** [comment]
Ah, that all makes sense. Thanks for the explanation @pestevez.
