### ISSUE TITLE
How to convert oembed div wrapped media to interactive format

### ISSUE THREAD

**Issue by pribeh** [facebook/facebook-instant-articles-sdk-php#237]
Hi,

I'm trying to figure out how to write a rule for converting embedded media in the non-iframe oembed format. This is dissimilar to iframes and I'm not sure it's even supported. Any ideas? Should it be converted to an iframe and then inserted into the figure class.op-interactive? 

Here's what the output looks like in the body of content for a Twitter embed.

```
<div data-oembed-url="https://twitter.com/aynehassan_/status/811203920898953216">
<twitterwidget class="twitter-tweet twitter-tweet-rendered" id="twitter-widget-4" style="position: static; visibility: visible; display: block; transform: rotate(0deg); width: 500px; margin: 10px auto; max-width: 100%; min-width: 220px;" data-tweet-id="811203920898953216"></twitterwidget>
<script async="" charset="utf-8" src="//platform.twitter.com/widgets.js"></script></div>
```

**Comment by vkama** [comment]
@pribeh Are you still needing help with this?

**Comment by pribeh** [comment]
No.
