### ISSUE TITLE
How to prevent & convert to &amp; when using "withSource"?

### ISSUE THREAD

**Issue by goodjack** [facebook/facebook-instant-articles-sdk-php#239]
# Steps required to reproduce the problem
```PHP
$adSource = "https://www.facebook.com/adnw_request?placement={$anPlacementId}&adtype=banner300x250";

$instantArticle->getHeader()->addAd(Ad::create()->withSource($adSource));
```

# Expected Result

```HTML
<figure class="op-ad">
  <iframe src="https://www.facebook.com/adnw_request?placement=PLACEMENT_ID&adtype=banner300x250"></iframe>
</figure>
```

# Actual Result

```HTML
<figure class="op-ad">
  <iframe src="https://www.facebook.com/adnw_request?placement=PLACEMENT_ID&amp;adtype=banner300x250"></iframe>
</figure>
```

How to prevent `&` convert to `&amp;` when using "withSource"?  Thanks.

**Comment by mustafamasa** [comment]
I'm having the same problem.
Did you solve it?

**Comment by kherlen** [comment]
I'm having the same problem

**Comment by everton-rosario** [comment]
Nice finding!
This was not covered into our testcases and indeed this is happening with the SDK itself.

On this PR  we can see the issue happening, it is something with the way PHP encodes content while saveXML() is called.
