### ISSUE TITLE
Transformer error logging

### ISSUE THREAD

**Issue by maciekpaprocki** [facebook/facebook-instant-articles-sdk-php#240]
# Steps required to reproduce the problem

1. Call `Facebook\InstantArticles\Parser::parse`

# Expected Result

I should receive instance of instant article if transformation worked. 
In case it failed I should receive exception or array of exceptions. 

# Actual Result

All debug messages are logged to output.

**Comment by everton-rosario** [comment]
All the SDK library has a warning mechanism, throwing exceptions only on programming errors or something that is not possible for most of the times be recovered automatically.

I'll improve the Parse error handling in a future PR, but this is the first step with this PR: #304
