### ISSUE TITLE
Using composer - error on log4php

### ISSUE THREAD

**Issue by tracyaxelson** [facebook/facebook-instant-articles-sdk-php#245]
# Steps required to reproduce the problem

1. Using Drupal 7 and Composer Manager, enabled Facebook Instant Articles module
2. composer.json is set to rebuild automatically - confirmed that FIA requirements are in file
3. php composer.phar install

# Expected Result

* installation of all dependencies in /sites/all/modules

# Actual Result

* Failure.  Here's the error:

`[RuntimeException]                                                                                                  
  Failed to execute git clone --no-checkout 'https://git-wip-us.apache.org/repos/asf/logging-log4php.git' 'myvendordirectorylocation/vendor/apache/log4php' --dissociate --reference 'mycomposerdirectorylocation/.composer/cache/  
  vcs/https---git-wip-us.apache.org-repos-asf-logging-log4php.git/' && cd '/myvendordirectorylocation/vend  
  or/apache/log4php' && git remote add composer 'https://git-wip-us.apache.org/repos/asf/logging-log4php.git' && git  
   fetch composer                                                                                                     
  Cloning into '/myvendordirectorylocation/vendor/apache/log4php'...                                        
  fatal: The remote end hung up unexpectedly                                                                          
                                             `

**Comment by yeah-sir** [comment]
@tracyaxelson are you still seeing this issue. This looks more like a git issue than something wrong on the repo. Can you try the solution [here](https://stackoverflow.com/a/15851500) to see if it fixes the issue?

**Comment by everton-rosario** [comment]
Per PR #304 you will need to use this calls to get the logging from transformation process (if wanted).

```
 $json_file = file_get_contents(__DIR__ . '/simple-rules.json');

        $instant_article = InstantArticle::create();
        $transformer = new Transformer();
        $transformer->loadRules($json_file);

        $html_file = file_get_contents(__DIR__ . '/simple.html');

        $transformer->setLogLevel(Transformer::LOG_DEBUG);
        $transformer->transformString($instant_article, $html_file);
        $result = $transformer->getLogs();
```
