### ISSUE TITLE
Hindi not Supporting 

### ISSUE THREAD

**Issue by kaushiksrv** [facebook/facebook-instant-articles-sdk-php#274]
# Steps required to reproduce the problem

1. I published Hindi article on my site and on production article something weird showing but on visiting **_Feed URL_** shows everything fine
![65](https://user-images.githubusercontent.com/29793077/32297817-6b8685b4-bf76-11e7-9b24-4e3eef45f3f9.PNG)

# Expected Result

* It should supoort hindi

# Actual Result

* 
![564848](https://user-images.githubusercontent.com/29793077/32297726-19deb1e6-bf76-11e7-99fc-ce76595b9663.PNG) i

**Comment by Arjunghimire** [comment]
same bro here always ..have you solved this problem?? plz tell me some idea ??

**Comment by yeah-sir** [comment]
@kaushiksrv The SDK supports languages of different charsets. Can you make sure you are providing the right charset in the `Transformer::transformString` method ?

**Comment by everton-rosario** [comment]
The SDK should be used with these instructions:
```
$transformer = new Transformer();
$yourHtmlStringIntoYourCharset = loadArticle(); // Do load your web html article content in the correct charset
$transformer->transformString(InstantArticle::create(), $yourHtmlStringIntoYourCharset, "your charset");
```
