### ISSUE TITLE
HTML tags in titles

### ISSUE THREAD

**Issue by nicolinuxfr** [facebook/facebook-instant-articles-sdk-php#28]
On my blog, I'm using HTML tags in the titles of my post, mainly `<em></em>` for the title of a work (like a movie). The plugin should strip HTML tags, since Instant Articles do not allow html in titles. 

For instance, here is what I have in Facebook app : 

![img_2649-me](https://cloud.githubusercontent.com/assets/2078386/14523764/a859927e-0235-11e6-97ae-a76a90b66434.jpg)

Here is the original URL : https://voiretmanger.fr/mommy-dolan/

**Comment by everton-rosario** [comment]
There are some tags accepted inside H1 and H2. Example: <b>, <a href>, <i>.

To make it work on your case you should transform it from: 
`<h1><em>Mommy</em>, Xavier Dolan</h1>`

to:

`<h1><em>Mommy</em>, Xavier Dolan</h1>`

To make it happen, just add the bellow lines to your rules.json file.

```javascript
            {
                "class": "ItalicRule",
                "selector" : "i"
            }
```

**Comment by nicolinuxfr** [comment]
Thanks for your answer ! Could you point me in the right direction to do this properly ? I guess I have something to add in my `functions.php` file ?

**Comment by nicolinuxfr** [comment]
Now that the feed has been updated, I can confirm this setting does not work. I still have titles like this one : 

`<h1>&lt;em&gt;Théo &amp; Hugo dans le même bateau&lt;/em&gt;, Olivier Ducastel et Jacques Martineau</h1>` 

If you can help me debug this… :-)

**Comment by nicolinuxfr** [comment]
OK, so I see now that I made a mistake in the format. I think it is correct now like this :

` { "rules": [{ "class": "italicRule", "selector": "em" }] }`

Can you confirm it's OK ? And if it is, it does not work, unfortunately…
