### ISSUE TITLE
Composer install log4php problem

### ISSUE THREAD

**Issue by closer01** [facebook/facebook-instant-articles-sdk-php#302]
I try to install with composer and it gives this error : 

```
  [RuntimeException]
  Failed to clone https://git-wip-us.apache.org/repos/asf/logging-log4php.git, git was not found, check that 
  it is in  stalled and in your PATH env.  'git' is not recognized as an internal or external command,
  operable program or batch file.
```

**Comment by Jayad** [comment]
Could you paste the exact command you tried?

**Comment by closer01** [comment]
@jayad composer require facebook/facebook-instant-articles-sdk-php

**Comment by Jayad** [comment]
1. Are you able to execute any other git commands? what is the o/p of git --help command from your current working directory. 
2. Could you try to execute the composer in verbose mode and share the o/p?   composer -vvv require facebook/facebook-instant-articles-sdk-php 
3. Which OS you are in? If Windows is the git to use from bash command is selected? Can u try appending the git.exe installed path in your PATH variable?

**Comment by closer01** [comment]
@Jayad 

1- I use Composer version 1.6.2
2 -  It gave same error
3- I use windows 10 , xammp. I have tried to install other packages but all gives same error. Do you have any recommendation?

**Comment by Jayad** [comment]
What's the op for git - - help.  Probably could you try to append the path of the git.exe to your  existing PATH variable in settings? 
This might help? 
http://www.chambaud.com/2013/07/08/adding-git-to-path-when-using-github-for-windows/


Please paste the o/p of composer -vvv require facebook/facebook-instant-articles-sdk-php

**Comment by everton-rosario** [comment]
This won't be needed once this PR #304 lands.
The transformation info/log can be obtained with the call `$transformer->getLogs()`.

Full contextualized after transformation call:
```
 $json_file = file_get_contents(__DIR__ . '/simple-rules.json');

        $instant_article = InstantArticle::create();
        $transformer = new Transformer();
        $transformer->loadRules($json_file);

        $html_file = file_get_contents(__DIR__ . '/simple.html');

        $transformer->setLogLevel(Transformer::LOG_DEBUG);
        $transformer->transformString($instant_article, $html_file);
        $result = $transformer->getLogs();
```
