### ISSUE TITLE
Bold element is using <b> tag but the official documentation explicitly say to not use it

### ISSUE THREAD

**Issue by lukasz-zaroda** [facebook/facebook-instant-articles-sdk-php#303]
This is something I don't get it, maybe someone will be able to help me.

Documentation at: https://developers.facebook.com/docs/instant-articles/sdk/transformer-rules clearly states:

> For example, to render text bold in an Instant Article, the <strong> tag must be used. But if your content makes use of <b> as a means to stylize text bold, you would find that your source markup is valid HTML, but ultimately is not valid Instant Articles markup.

But the `Bold` element in this SDK is created in the following way:

https://github.com/facebook/facebook-instant-articles-sdk-php/blob/adcaf6ee43cd2b43ee81b2a84305ca65e83e50fc/src/Facebook/InstantArticles/Elements/Bold.php#L37-L52

So it's being created as a `b` tag. Why?

**Comment by everton-rosario** [comment]
Hey @lukasz-zaroda are you having some issue using `<b>` content or `<strong>`?
Can you elaborate a little more your use case scenario so we can help properly?

Even though our documentation states about not being the proper use of `<b/>` tags we still support it for retro-compatibility related issues. 

Basically the intended output from the SDK is a valid Instant Article markup content file.
To perform that, we "interpret" the HTML based on the configured rules and create the Elements (which is a object tree that represents a valid Instant Article element) then we just render it as Instant Article html file so we can have that content ingested through our ingestion endpoints.

Let me know more details about the issue you are facing.

Closing it for now, and reopening in case of more info informed.

Thanks for reaching out and using our tools.

**Comment by lukasz-zaroda** [comment]
The issue is, I think, that if documentation clearly states that `b` is no a valid Instant Article tag but supports it anyway, then we are risking that they will drop that support at anytime, and should change this to "strong" or to avoid confusion, add another element `Strong` and mark `Bold` as deprecated.

**Comment by lukasz-zaroda** [comment]
And I realize that saying "they" in this context is not accurate because you are the same people, but there always can happen some lack of coordination, or someone can simply misunderstand things by reading code of this SDK, and can start using `b` himself :) .

**Comment by everton-rosario** [comment]
Yes, just found that reference you mentioned on the docs.
Indeed it was on the roadmap a plan to remove it, but given the usage, `<b>` tags will still be supported.

Thanks for raising this up, I've updated the docs mentioning about that particular case on usage of `<b>` vs `<strong>`.
