### ISSUE TITLE
Auto-strip empty <p /> tags

### ISSUE THREAD

**Issue by m4olivei** [facebook/facebook-instant-articles-sdk-php#31]
A lot of our content has `<p>&nbsp;</p>` in the content.  This is kind of a bad habit of editors to introduce vertical space in an article, but I digress.  Also, I've found that loading up HTML to pass to the transformer can also introduce empty `<p></p>` tags.  For example:

```php
$html = '<p><h2>I'm a real title</h2></p>';
$document = new \DOMDocument();
$output = '<!doctype html><html><head><meta charset="utf-8" /></head><body>' . $html . '</body>';
@$document->loadHTML($output);
$transformer->transform($body, $document);
```
In the output you get:
```html
<p></p>
<h2>I'm a real title</h2>
```
Of course, this is bad source HTML, headings are not allowed as children of `<p>`, so we'll look at fixing our source HTML, but here an empty paragraph is allowed to pass through to Facebook, where there is no reason for it in the context of FBIA.

Is there a way that the SDK could strip out empty `<p>` tags?  Or is there a Transformer rule that you can write to strip out empty `<p>` tags (I've tried this to no avail..)?

**Comment by scottrigby** [comment]
Regarding `<p>&nbsp;</p>`, we've tried several XPath selector variations, to no avail. Here is the general ignore rule setup we're testing:
```
  $config = array(
    'class' => 'IgnoreRule',
    'selector' => $selector,
  );
  $rule = IgnoreRule::createFrom($config);
  $transformer->addRule($rule);
```
where `$selector` has been `//*[text()="&nbsp;"]`, `//*[text()="\u0160"]`, `//*[text()=codepoints-to-string((160))]` (which breaks), and other variations using `normalize-space()`. Is anyone able to find a way to make this work, or would we need to introduce changes in the SDK to allow it?

**Comment by m4olivei** [comment]
OK, so I think I've worked out a nice custom Rule class that I'm happy with that works for this purpose:

```php
<?php

/**
 * @file
 * Contains \EmptyRule
 */

use Facebook\InstantArticles\Elements\TextContainer;
use Facebook\InstantArticles\Transformer\Rules\ConfigurationSelectorRule;

/**
 * Matches empty nodes given a selector.  Here empty nodes are defined as nodes
 * in a DOMDocument that have no children, or have only text children containing
 * whitespace characters.
 */
class EmptyRule extends ConfigurationSelectorRule {

  public function __construct() {
  }

  public static function create() {
    return new EmptyRule();
  }

  public static function createFrom($configuration) {
    return self::create()->withSelector($configuration['selector']);
  }

  public function getContextClass() {
    return TextContainer::class;
  }

  public function matchesContext($context) {
    return TRUE;
  }

  /**
   * @param \DOMNode $node
   * @return mixed
   */
  public function matchesNode($node) {
    // We're only interested in elements here, testing if they are empty.
    if ($node->nodeType !== XML_ELEMENT_NODE) {
      return FALSE;
    }

    // Limit by the selector passed in the configuration.
    if (!parent::matchesNode($node)) {
      return FALSE;
    }

    // Match iff the node has no children and/or all children are empty text
    // nodes.
    if ($node->hasChildNodes()) {
      /* @var \DOMNode $child */
      foreach ($node->childNodes as $child) {
        if ($child->nodeName !== '#text') {
          return FALSE;
        }
        else {
          // @see https://stackoverflow.com/a/27990195/142145
          $trimmed = trim($child->nodeValue, " \t\n\r\0\x0B\xC2\xA0");
          if (!empty($trimmed)) {
            return FALSE;
          }
        }
      }
    }

    return TRUE;
  }

  public function apply($transformer, $context, $element) {
    return $context;
  }
}
```
Then assuming you've got a `\Facebook\InstantArticles\Transformer\Transformer` instance called `$transfomer` kicking around, add a config rule like so:
```php
$transformer->addRule(
    EmptyRule::createFrom(array(
      'class' => 'EmptyRule',
      'selector' => '//p|//div|//span',
    ))
  );
```
The method `EmptyRule::matchesNode` is the key.  It'll match any element node, matched by the selector given, that either has no child nodes or has only text child nodes containing only whitespace.  This reeeeeally annoying part is the need for this trim statement: `trim($child->nodeValue, " \t\n\r\0\x0B\xC2\xA0")`, which will match the usual whitespace suspects, *but also* NBSP.

Working for me so far.  If you guys are into this, I'd be up for re-jigging this into a proper pull request.

**Comment by everton-rosario** [comment]
Hey @m4olivei , thanks for digging into this!

This is cool that this solved your cases. I just want to warn you to be aware of this usage.
The Transformer Rules were not designed to have a double pass on same node. So if one specific node is selected by context and the selector, it wont leave this node for another rule.

This way, the empty rule will need a selector that selects only empty #text content.


Im working on a solution right now and will have a pull request soon.
This PR will be:
- All Elements will have a method isValid()
- toDOMElements will have an if (!$this->isValid()) -> Wont output itself.
- Transformer will check all isValid() from elements, if not valid, will add a warning to the transformation

This way we wont:
- Output invalid/empty elements
- Wont fail silently (because we will add warnings to the Transformer process)

**Comment by m4olivei** [comment]
@everton-rosario yeah your right.  It's only working for me b/c I have it as the last rule added to the Transformer, which means its the first rule that gets checked against all nodes.

Sounds like a neat solution, look forward to testing it.  Thanks for looking into this as well!

**Comment by Faiyaz** [comment]
Any update on this @everton-rosario.

**Comment by everton-rosario** [comment]
Yes @Faiyaz.
Please follow and also help review this PR: https://github.com/facebook/facebook-instant-articles-sdk-php/pull/71
