### ISSUE TITLE
symfony/css-selector requirement

### ISSUE THREAD

**Issue by m4olivei** [facebook/facebook-instant-articles-sdk-php#321]
# Steps required to reproduce the problem

1. Install Drupal >= 8.4.0 with the FBIA module 8.x-2.x branch, which requires the FBIA SDK at `^1.0.0`

# Expected Result

* Composer installs latest version of FBIA SDK

# Actual Result

* Composer installs version 1.7.0 of FBIA SDK

After some debugging, it turns out that this result is due to conflicting version constraints for `symfony/css-selector` between Drupal core and the FBIA PHP SDK. Drupal core as of version 8.4.0 requires `symfony/css-selector:~3.2.8` (http://cgit.drupalcode.org/drupal/tree/core/composer.json?id=8.4.0#n49). The FBIA SDK requires `2.8.*` (https://github.com/facebook/facebook-instant-articles-sdk-php/blob/master/composer.json#L14). Thus composer will go back to 1.7.0 of the FBIA SDK to satisfy both, which had a more liberal version constraint of `symfony/css-selector:2.8.* || ^3.0`.

Can we set the version constraint back to what it was so that Drupal and others that also need to use newer `symfony/css-selector` can use the latest FBIA SDK? What were the reasons for regressing back to strictly `2.8.*`?

**Comment by mburak** [comment]
Hey @m4olivei, thanks for flagging this up! 
We are working on the fix for this. It will be ready soon.

**Comment by mburak** [comment]
Fixed by #319

**Comment by m4olivei** [comment]
Ah! Not sure how I missed that PR, thanks!

**Comment by m4olivei** [comment]
@mburak when can we expect a new release with this code?

**Comment by mburak** [comment]
@m4olivei we just released v1.9.1 with that fix. Have a good day!
