### ISSUE TITLE
Failed Connection with graph.facebook.com

### ISSUE THREAD

**Issue by aminkhannsu** [facebook/facebook-instant-articles-sdk-php#323]
# Steps required to reproduce the problem

1. I have post the article data and it returns error.

# Expected Result

* Success

# Actual Result

* array(1) { ["error"]=> string(58) "Failed connect to graph.facebook.com:443; No route to host" }

**Comment by aminkhannsu** [comment]
Need help. Urgent...!!!

**Comment by everton-rosario** [comment]
Looks like you are having some connection issues to reach out to Facebook graph API servers.
We are not experiencing any issues on the graph API end. 

Does your server has ACL or permissions to outbound connections?

We can reopen if you have any reproducible steps for a better investigation
