### ISSUE TITLE
Installation problem on laravel 5.6

### ISSUE THREAD

**Issue by amjad-eremnews** [facebook/facebook-instant-articles-sdk-php#332]
Installing using composer `composer require facebook/facebook-instant-articles-sdk-php`

#Result:

` Problem 1
    - Conclusion: don't install facebook/facebook-instant-articles-sdk-php v1.9.2
    - Conclusion: don't install facebook/facebook-instant-articles-sdk-php v1.9.1
    - Conclusion: remove symfony/css-selector v4.1.0
    - Installation request for facebook/facebook-instant-articles-sdk-php ^1.9 -> satisfiable by facebook/facebook-instant-articles-sdk-php[v1.9.0, v1.9.1, v1.9.2].
    - Conclusion: don't install symfony/css-selector v4.1.0
    - facebook/facebook-instant-articles-sdk-php v1.9.0 requires symfony/css-selector 2.8.* -> satisfiable by symfony/css-selector[2.8.x-dev, v2.8.0, v2.8.0-BETA1, v2.8.1, v2.8.10, v2.8.11, v2.8.12, v2.8.13, v2.8.14, v2.8.15, v2.8.16, v2.8.17, v2.8.18, v2.8.19, v2.8.2, v2.8.20, v2.8.21, v2.8.22, v2.8.23, v2.8.24, v2.8.25, v2.8.26, v2.8.27, v2.8.28, v2.8.29, v2.8.3, v2.8.30, v2.8.31, v2.8.32, v2.8.33, v2.8.34, v2.8.35, v2.8.36, v2.8.37, v2.8.38, v2.8.39, v2.8.4, v2.8.40, v2.8.41, v2.8.42, v2.8.5, v2.8.6, v2.8.7, v2.8.8, v2.8.9].
    - Can only install one of: symfony/css-selector[2.8.x-dev, v4.1.0].
    - Can only install one of: symfony/css-selector[v2.8.0, v4.1.0].
    - Can only install one of: symfony/css-selector[v2.8.0-BETA1, v4.1.0].
    - Can only install one of: symfony/css-selector[v2.8.1, v4.1.0].
..... 
`

**Comment by everton-rosario** [comment]
Hey @amjad-eremnews can you please check if this enables you to build it with more php and sub dependencies?

I've added an extra layer of compatibility.

For testing it, you will need to install it locally:

```
git clone https://github.com/facebook/facebook-instant-articles-sdk-php.git
cd facebook-instant-articles-sdk-php
composer update
composer install
```

Please reopen or ping me if this is still a problem for your environment build.
