### ISSUE TITLE
Transformer->loadRules($rules_file) - trying to load rule classes outside the package namespace

### ISSUE THREAD

**Issue by Faiyaz** [facebook/facebook-instant-articles-sdk-php#35]
I am getting 'Warning: Class .. not found' when using loadRules method. Seems like the try catch block inside loadRules needs to flip the conditions order. 

```php
try {
    $factory_method = new \ReflectionMethod($clazz, 'createFrom');
} catch (\ReflectionException $e) {
    $factory_method =
        new \ReflectionMethod(
            'Facebook\\InstantArticles\\Transformer\\Rules\\'.$clazz,
            'createFrom'
        );
}
```

**Comment by Faiyaz** [comment]
Never mind. This apparently isn't an issue anymore on my end. Probably my setup wasn't correct. Closing issue. Thanks.

**Comment by everton-rosario** [comment]
Sorry for the late follow up on this thread.
Thank you for using the SDK and feel free to post issues you find or even Pull requests.
We are trying our best to keep everything up to date.
