### ISSUE TITLE
Question: Can we have a Travis CI integration?

### ISSUE THREAD

**Issue by localheinz** [facebook/facebook-instant-articles-sdk-php#40]
Some of the other projects, for example

* https://github.com/facebook/facebook-php-sdk-v4

have it, can we have one, too?

This will increase everyone's confidence when submitting and accepting pull requests, won't it?

**Comment by simonengelhardt** [comment]
Yes we can 👍  We will set this up.

**Comment by localheinz** [comment]
@simonengelhardt 

😃 Nice!
