### ISSUE TITLE
Installation fails, requires older version of syfony/css-selector

### ISSUE THREAD

**Issue by jose-zapata** [facebook/facebook-instant-articles-sdk-php#45]
I have installed symfony/css-selector v 3.0.4 and when I try to install this package it says that it requires  symfony/css-selector 2.8.* and thus it won't install. I can't downgrade symfony/css-selector because it's required for another package. Is this something that can be fixed?

**Comment by everton-rosario** [comment]
Hello jose-zapata. Thank you for your feedback and for using this SDK.
We downgraded the version of CSS-Selector to 2.8.* because this 2.8.* version is compatible with PHP 5.4 and this SDK should be compatible with PHP 5.4 as well.

If needed, run:
`composer update && composer install`
