### ISSUE TITLE
Cross calls in the transformer and apply files slowing down the generation

### ISSUE THREAD

**Issue by katazina** [facebook/facebook-instant-articles-sdk-php#49]
I'm using the Instant Articles for WP plugin, which is works fine.
They are using this sdk and the problem is that the generation of the feed is very slow and it timeouts.
The problem is in the sdk, not in the plugin.

`\src\Facebook\InstantArticles\Transformer\Transformer.php`
The **transform function** calls the **$rule->apply(...)**
That's ok, but some of the apply rules call back the transfrom function.

For example it is a problem if you have a post with many images, then for one post to generate in the feed, it takes 5-10 seconds.
`ImageRule.php: $transformer->transform($image, $node);`
So, if the timeout is set to 180 second, then I can't generate more than 20 posts without a timeout, if they have multiple images. And for obvious reasons I don't want to raise the timeout.

I looked just for images, but the ParagraphRule and others also call back to the transformer function and slows down the process.

**Comment by simonengelhardt** [comment]
Thanks for reporting. This should be fixed by #46
