### ISSUE TITLE
Problem with Custom Shortcodes Video Embed

### ISSUE THREAD

**Issue by eustasskid** [facebook/facebook-instant-articles-sdk-php#72]
Hello, I'm using custom shortcodes to embed youtube and facebook videos using their respective Javascript APIs. Example: [customyoutube id="XXXXX"] where XXXXX is the youtube video ID. The reason for this is that I added callback functions when the video finished playing. Now my problem is, Instant Articles displays the javascript part of the shortcode as paragraph block in the Instant Articles. Please kindly advice me how to transform the shortcode so that the output is IA compliant video embed. Thank you in advance.

**Comment by demoive** [comment]
I see you've opened the same issue on the WordPress plugin. That is the more appropriate place for the solution so I'm marking this as closed.

https://github.com/Automattic/facebook-instant-articles-wp/issues/171
