### ISSUE TITLE
Handling images inside paragraphs in Transformer

### ISSUE THREAD

**Issue by joevanni99** [facebook/facebook-instant-articles-sdk-php#81]
WYSISWYG Editors used in CMSs like drupal or WordPress often wrap `<img>` tags around a `<p>` tag. I was able to eliminate the wrap with preg_replace, but I am having issues with images inside a longer paragraph. Inserting an image inside a paragraph is valid according to html, but facebook instant articles requires any image to be wrapped inside a `<figure>` tag. I think that the ImageRule should be able to correctly handle images inside paragraphs.

**Comment by everton-rosario** [comment]
This was fixed on the PR #124
Can you double check it @joevanni99 

Check if you'd like to join us on this event meeting we will do about IA:
http://goo.gl/forms/rZc8LKltI04bsUoF2

**Comment by agent932** [comment]
I am having this issue with the wordpress plugin:
"Please include all of the images found in the web article. Also, please make sure that the <img> tag is not wrapped in <p> tags which will cause the image to not render correctly:"
is there a custom transformer rule to resolve this?
*sorry if this is not the correct forum for this question
