### ISSUE TITLE
Transformer drops content in pharagraph if there is image too

### ISSUE THREAD

**Issue by katazina** [facebook/facebook-instant-articles-sdk-php#91]
The content:
`<p><a href="http://example.com/image.jpg"><img class="alignnone size-medium wp-image-45" src="http://example.com/image.jpg" alt="imagealt" width="300" height="169" /></a>Some text comes here and some more and more ... and some.</p>`

After the closing `<a>` tag, there is some text, and the sdk drops that text.

Same happens when I reorder the inside:
`<p>Some text comes here and some more and more ... and some.<a href="http://example.com/image.jpg"><img class="alignnone size-medium wp-image-45" src="http://example.com/image.jpg" alt="imagealt" width="300" height="169" /></a></p>`

Or if there is text before and after:
`<p>Some text comes here and some more and more ... and some.<a href="http://example.com/image.jpg"><img class="alignnone size-medium wp-image-45" src="http://example.com/image.jpg" alt="imagealt" width="300" height="169" /></a>Some text comes here and some more and more ... and some.</p>`

The below expexted result is just for the first content example.

# Expected Result

```
<figure>
        <img src="http://example.com/image.jpg"/>
</figure>
<p>Some text comes here and some more and more ... and some.</p>
```

# Actual Result

```
<figure>
        <img src="http://example.com/image.jpg"/>
</figure>
```

**Comment by demoive** [comment]
Also reported on the WordPress forums:

https://wordpress.org/support/topic/articles-that-begin-with-an-image-are-stripping-out-first-paragraph?replies=2
https://wordpress.org/support/topic/content-within-div-missing-in-instant-article-and-other-content-missing?replies=2

**Comment by everton-rosario** [comment]
@katazina Can you help us validating this PR that fixes your issue?

**Comment by katazina** [comment]
unfortunately it's not working for me.
I downloaded a patch file, after that I downloaded the whole paragraph-with-image branch, but no success.

Try with the attached post content.
[paragraph-image.txt](https://github.com/facebook/facebook-instant-articles-sdk-php/files/309676/paragraph-image.txt)

**Comment by diegoquinteiro** [comment]
@katazina did you configure the new rule on your ruleset JSON? If so, can you share how your JSON looks like?

**Comment by katazina** [comment]
Sorry, it's night here. I refreshed the json file, but now I got an error when the feed is generated:

`PHP Fatal error:  Call to undefined method Facebook\InstantArticles\Elements\InstantArticle::appendText() in facebook-instant-articles-sdk-php/src/Facebook/InstantArticles/Transformer/Rules/TextNodeRule.php on line 48`

I'm trying to figure it out what happened.

**Comment by katazina** [comment]
I'm sorry, I had no time to check it.
Now I did.
It's half good, but still not perfect.

Here is a code which on the transformer fails:
```
<p><img class="alignleft size-medium wp-image-5545280" src="https://pixabay.com/static/uploads/photo/2015/10/01/20/15/landscape-967630_960_720.jpg" alt="something" width="320" height="213" />almafa fsdfsdff8</p>
<p>sfsdfsd</p>
<p>3333sdfsdfsd</p>
<ul>
<li>some text <a href="https://pixabay.com/static/uploads/photo/2015/10/01/20/15/landscape-967630_960_720.jpg"><img src="https://pixabay.com/static/uploads/photo/2015/10/01/20/15/landscape-967630_960_720.jpg" width="600" height="360" /></a></li>
</ul>
<p>sfdsfsdf</p>
<p>sfsdfsd</p>
<p>fssd</p>
```

And here is the current result:
```
<figure>
    <img src="https://pixabay.com/static/uploads/photo/2015/10/01/20/15/landscape-967630_960_720.jpg"/>
</figure>
<p>almafa fsdfsdff8</p>
<p>sfsdfsd</p>
<p>3333sdfsdfsd</p>
<ul>
    <li>some text <a href="https://pixabay.com/static/uploads/photo/2015/10/01/20/15/landscape-967630_960_720.jpg"></a></li>
</ul>
<p>sfdsfsdf</p>
<p>sfsdfsd</p>
<p>fssd</p>
```

You can see, beside the **some text** the image is not processed, but an empty **a** tag was kept.

With the p tag in the first line, it worked perfectly.
