### ISSUE TITLE
Transformer drops images from li

### ISSUE THREAD

**Issue by katazina** [facebook/facebook-instant-articles-sdk-php#92]
The content:

```
<ul>
<li>
some text <a href="http://example.com/"><img src="http://example.com/image.jpg" width="600" height="360" /></a>
</li>
</ul>
```
After the transformer is done, there is no image.

# Expected Result

```
<ul>
        <li>some text</li>
</ul>
<figure>
        <img src="http://example.com/image.jpg"/>
</figure>
```

# Actual Result

```
<ul>
        <li>some text</li>
</ul>
```
The image is missing.

**Comment by everton-rosario** [comment]
@katazina Can you help us validating this PR that fixes your issue?

**Comment by katazina** [comment]
no luck with that either, like in [https://github.com/facebook/facebook-instant-articles-sdk-php/issues/91](url)
